import { Track, SortType } from '../types';

export const name = 'My Playlist';
export const currentSortType: SortType = 'DATE-ADDED-NEWEST';
export const sortTypes: SortType[] = ['DATE-ADDED-NEWEST', 'DATE-ADDED-OLDEST', 'ALPHABETICAL'];

export const tracks: Track[] = [
  {
    id: 'TtqTG6',
    title: 'Everybody Keep Running (EDM / Instrumental)',
    description: 'An energetic and inspirational EDM-house track composed by Zight. A song for the post-pandemic world. A gift to all marathon lovers.',
    artist: 'Zight',
    album: null,
    art: '/images/Zight---Everybody-Keep-Running-(EDM-_-Instrumental).jpg',
    audio: '/audio/Zight---Everybody-Keep-Running-(EDM-_-Instrumental).mp3',
    duration: '02:54',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Pop',
    dateReleased: '10/10/2021',
    dateAdded: '10/10/2021',
    url: 'https://freemusicarchive.org/music/zight/single/everybody-keep-running-edm-instrumental',
  },
  {
    id: 'ltXNQ7',
    title: 'Fly Away (EDM / Instrumental)',
    description: 'An energetic and inspirational track. Ideal for projects where you need the energy and motivation to pursue freedom.',
    artist: 'Zight',
    album: null,
    art: '/images/Zight---Fly-Away-(EDM-_-Instrumental).jpeg',
    audio: '/audio/Zight---Fly-Away-(EDM-_-Instrumental).mp3',
    duration: '03:33',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Pop',
    dateReleased: '12/10/2021',
    dateAdded: '12/10/2021',
    url: 'https://freemusicarchive.org/music/zight/single/fly-away-edm-instrumental',
  },
  {
    id: 'SfTINP',
    title: 'Daisy (EDM / Instrumental)',
    description: 'A super catchy electro-pop song. Ideal for media projects targeting young audience.',
    artist: 'Zight',
    album: null,
    art: '/images/Zight---Daisy-(EDM-_-Instrumental).jpeg',
    audio: '/audio/Zight---Daisy-(EDM-_-Instrumental).mp3',
    duration: '03:23',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Pop',
    dateReleased: '12/10/2021',
    dateAdded: '12/10/2021',
    url: 'https://freemusicarchive.org/music/zight/single/daisy-edm-instrumental',
  },
  {
    id: 'A7qak5',
    title: 'End Of The Road',
    description: null,
    artist: 'Anthem of Rain',
    album: 'Freedom',
    art: '/images/Anthem-of-Rain.jpeg',
    audio: '/audio/Anthem-of-Rain---End-Of-The-Road.mp3',
    duration: '03:23',
    instrumental: false,
    explicit: 'radio-safe',
    genres: 'Pop, Easy Listening, Soul-RnB, Easy Listening: Vocal, hiphop',
    dateReleased: '06/22/2021',
    dateAdded: '06/22/2021',
    url: 'https://freemusicarchive.org/music/anthem-of-rain/freedom/end-of-the-road',
  },
  {
    id: 'SIJEKH',
    title: 'All For Nothing',
    description: null,
    artist: 'Anthem of Rain',
    album: 'Freedom',
    art: '/images/Anthem-of-Rain.jpeg',
    audio: '/audio/Anthem-of-Rain---All-For-Nothing.mp3',
    duration: '04:38',
    instrumental: false,
    explicit: 'radio-safe',
    genres: 'International, Pop, Easy Listening, Soundtrack, Easy Listening: Vocal, Piano, Acoustic',
    dateReleased: '06/22/2021',
    dateAdded: '06/22/2021',
    url: 'https://freemusicarchive.org/music/anthem-of-rain/freedom/all-for-nothing',
  },
  {
    id: 'pr45dw',
    title: 'Rock This House',
    description: null,
    artist: 'Anthem of Rain',
    album: 'Freedom',
    art: '/images/Anthem-of-Rain.jpeg',
    audio: '/audio/Anthem-of-Rain---Rock-This-House.mp3',
    duration: '03:23',
    instrumental: false,
    explicit: 'radio-safe',
    genres: 'International, Pop, Easy Listening, Electronic, Easy Listening: Vocal, Minimal Electronic, Dance',
    dateReleased: '06/22/2021',
    dateAdded: '06/22/2021',
    url: 'https://freemusicarchive.org/music/anthem-of-rain/freedom/rock-this-house',
  },
  {
    id: 'xwwFpN',
    title: 'Through My Astrolabe',
    description: 'track from Polyphony Più\'s 2018 Surround Fundamental Shifts and Exhibitions Lp.',
    artist: 'Ov Moi Omm',
    album: null,
    art: '/images/Ov-Moi-Omm---Through-My-Astrolabe.jpg',
    audio: '/audio/Ov-Moi-Omm---Through-My-Astrolabe.mp3',
    duration: '03:09',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Pop, Electronic, Experimental Pop, Glitch, Minimal Electronic, Synth Pop',
    dateReleased: '11/14/2021',
    dateAdded: '11/14/2021',
    url: 'https://freemusicarchive.org/music/ov-moi-omm/single/through-my-astrolabe',
  },
  {
    id: 'm6nXqh',
    title: 'A Night In Bandung',
    description: 'track from Polyphony Più\'s 2016 Oscillating Illuminations Lp.',
    artist: 'Ov Moi Omm',
    album: null,
    art: '/images/Ov-Moi-Omm---A-Night-In-Bandung.jpg',
    audio: '/audio/Ov-Moi-Omm---A-Night-In-Bandung.mp3',
    duration: '03:25',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Field Recordings, Experimental, Electroacoustic, Ambient Electronic, Experimental Pop, Asia',
    dateReleased: '11/14/2021',
    dateAdded: '11/14/2021',
    url: 'https://freemusicarchive.org/music/ov-moi-omm/single/a-night-in-bandung',
  },
  {
    id: 'HvoEaA',
    title: 'Within this Sphere lie 71 Stars',
    description: 'track from Polyphony Più\'s 2021 Polyphony Più IV Lp.',
    artist: 'Ov Moi Omm',
    album: null,
    art: '/images/Ov-Moi-Omm---Within-this-Sphere-lie-71-Stars.jpg',
    audio: '/audio/Ov-Moi-Omm---Within-this-Sphere-lie-71-Stars.mp3',
    duration: '12:58',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Avant-Garde, Electronic, Soundtrack, Experimental, Drone, Experimental Pop, Glitch, Downtempo',
    dateReleased: '11/14/2021',
    dateAdded: '11/14/2021',
    url: 'https://freemusicarchive.org/music/ov-moi-omm/single/within-this-sphere-lie-71-stars',
  },
  {
    id: 'tHqFxT',
    title: 'All is Shadow and Light',
    description: 'track from Ihsan & The Cabinet of Dr. Caligari\'s 2021 Croquis et thèmes Lp.',
    artist: 'Ov Moi Omm',
    album: null,
    art: '/images/Ov-Moi-Omm---All-is-Shadow-and-Light.jpg',
    audio: '/audio/Ov-Moi-Omm---All-is-Shadow-and-Light.mp3',
    duration: '03:34',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Noise, Experimental, Ambient Electronic, Glitch, Minimal Electronic',
    dateReleased: '11/13/2021',
    dateAdded: '11/13/2021',
    url: 'https://freemusicarchive.org/music/ov-moi-omm/single/all-is-shadow-and-light',
  },
  {
    id: 'fn0N3v',
    title: 'Dirty Infection - Acid Mix',
    description: null,
    artist: 'Arndt Stelter',
    album: null,
    art: '/images/Arndt-Stelter---Dirty-Infection---Acid-Mix.jpeg',
    audio: '/audio/Arndt-Stelter---Dirty-Infection---Acid-Mix.mp3',
    duration: '04:58',
    instrumental: false,
    explicit: null,
    genres: 'Pop, Electronic, Experimental, Industrial, New Wave, Unclassifiable',
    dateReleased: '10/16/2021',
    dateAdded: '10/16/2021',
    url: 'https://freemusicarchive.org/music/arndt-stelter/single/dirty-infection-acid-mix',
  },
  {
    id: 'Fx4ICR',
    title: 'Peaces of a Soul',
    description: null,
    artist: 'Arndt Stelter',
    album: null,
    art: '/images/Arndt-Stelter---Peaces-of-a-Soul.jpeg',
    audio: '/audio/Arndt-Stelter---Peaces-of-a-Soul.mpg',
    duration: '05:55',
    instrumental: false,
    explicit: null,
    genres: 'Classical, Soundtrack, Composed Music',
    dateReleased: '10/16/2021',
    dateAdded: '10/16/2021',
    url: 'https://freemusicarchive.org/music/arndt-stelter/single/peaces-of-a-soul',
  },
  {
    id: 'K6ujFC',
    title: 'Someone Real',
    description: '"Someone Real" Jenna Jay\'s first single is about wanting new love after going through a toxic relationship full of lies, betrayal, and heartbreak. It spills the raw emotions and pain about hoping to find pure realness in a person again. It talks about finding someone for once who is genuine and doesn\'t put on a fake mask.',
    artist: 'Jenna Jay',
    album: null,
    art: '/images/Jenna-Jay---Someone-Real---Jenna-Jay.jpeg',
    audio: '/audio/Jenna-Jay---Someone-Real---Jenna-Jay.mp3',
    duration: '03:49',
    instrumental: false,
    explicit: 'radio-safe',
    genres: 'Pop',
    dateReleased: '08/30/2021',
    dateAdded: '08/30/2021',
    url: 'https://freemusicarchive.org/music/jenna-jay/single/someone-real-jenna-jay',
  },
  {
    id: 'bWCoSm',
    title: 'Aqueduct',
    description: null,
    artist: 'Evan Schaeffer',
    album: null,
    art: '/images/Evan-Schaeffer.jpeg',
    audio: '/audio/Evan-Schaeffer---Aqueduct.mp3',
    duration: '02:33',
    instrumental: true,
    explicit: null,
    genres: 'Pop, Easy Listening, Electronic',
    dateReleased: '12/08/2021',
    dateAdded: '12/08/2021',
    url: 'https://freemusicarchive.org/music/Evan_Schaeffer/Glow_1216/aqueduct',
  },
  {
    id: 'WmRNQf',
    title: 'Chimera',
    description: null,
    artist: 'Evan Schaeffer',
    album: null,
    art: '/images/Evan-Schaeffer.jpeg',
    audio: '/audio/Evan-Schaeffer---Chimera.mp3',
    duration: '03:43',
    instrumental: false,
    explicit: null,
    genres: 'Pop, Chill-out, Instrumental',
    dateReleased: '08/07/2017',
    dateAdded: '08/07/2017',
    url: 'https://freemusicarchive.org/music/Evan_Schaeffer/Big_Splash/Evan_Schaeffer_-_03_-_Chimera',
  },
  {
    id: 'q9tbVR',
    title: 'Chill Breeze',
    description: null,
    artist: 'Evan Schaeffer',
    album: null,
    art: '/images/Evan-Schaeffer.jpeg',
    audio: '/audio/Evan-Schaeffer---Chill-Breeze.mp3',
    duration: '03:27',
    instrumental: false,
    explicit: null,
    genres: 'Pop, Electronic, Instrumental',
    dateReleased: '08/23/2017',
    dateAdded: '08/23/2017',
    url: 'https://freemusicarchive.org/music/Evan_Schaeffer/Glow_1216/Evan_Schaeffer_-_14_-_Chill_Breeze_1474',
  },
  {
    id: 'mVhNqw',
    title: 'Slow Burn',
    description: 'Supported by a swing beat, the atmospheric piano track gradually increases to climax in an electronic pop melody. The track is suitable for a wide vareity of explanatory videos, animations and technical videos. Moods: driving, serious, atmospheric, upbeat Licence: "Slow Burn" by Johannes Weber, Fachhochschule Dortmund, CC BY 4.0',
    artist: 'Johannes Weber x Fachhochschule Dortmund',
    album: null,
    art: '/images/Fallback-Image-Track-500.jpeg',
    audio: '/audio/Johannes-Weber-x-Fachhochschule-Dortmund---Slow-Burn.mp3',
    duration: '03:56',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Pop, Easy Listening, Electronic',
    dateReleased: '12/08/2021',
    dateAdded: '12/08/2021',
    url: 'https://freemusicarchive.org/music/johannes-weber/single/slow-burn',
  },
  {
    id: 'Qj2jy8',
    title: 'Meadow Call',
    description: 'This track is marked by a light and refreshing groove with a melodic climax. Funk elements and a smooth groove embellish a dynamic bassline and a dreamy guitar solo. The track is suitable for all kinds of explanatory videos including introductions, instructional videos, and image clips. Moods: light, refreshing, dynamic, positive, friendly, pleasant, dreamy "Meadow Call" by Jan-Michael Hökenschnieder, Fachhochschule Dortmund, CC BY 4.0',
    artist: 'Jan-Michael Hökenschnieder x Fachhochschule Dortmund',
    album: null,
    art: '/images/Fallback-Image-Track-500.jpeg',
    audio: '/audio/Jan-Michael-Hökenschnieder-x-Fachhochschule-Dortmund---Meadow-Call.mp3',
    duration: '03:11',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Jazz, Pop, Easy Listening, Funk',
    dateReleased: '12/08/2021',
    dateAdded: '12/08/2021',
    url: 'https://freemusicarchive.org/music/jan-michael-hokenschnieder/single/meadow-call',
  },
  {
    id: 'L6i9Xj',
    title: 'Digital Tears',
    description: 'Electronic groove track.',
    artist: 'Pariah',
    album: null,
    art: '/images/Pariah---Digital-Tears.jpeg',
    audio: '/audio/Pariah---Digital-Tears.mp3',
    duration: '04:59',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Pop, Electronic, Soundtrack, Experimental, Ambient Electronic, Radio Art',
    dateReleased: '08/18/2021',
    dateAdded: '08/18/2021',
    url: 'https://freemusicarchive.org/music/pariah/single/digital-tears',
  },
  {
    id: '82BeEt',
    title: 'Boots & Pants',
    description: null,
    artist: 'Monkey Warhol',
    album: 'Boots & Pants EP',
    art: '/images/Monkey-Warhol---Boots-&-Pants.jpg',
    audio: '/audio/Monkey-Warhol---Boots-&-Pants.mp3',
    duration: '02:45',
    instrumental: false,
    explicit: null,
    genres: 'Pop, Disco, Electronic, Electro-Punk, Experimental Pop, Techno, Dance, Synth Pop',
    dateReleased: '08/05/2021',
    dateAdded: '08/05/2021',
    url: 'https://freemusicarchive.org/music/Monkey_Warhol/boots-pants-ep/boots-pants',
  },
  {
    id: 'nBXgrb',
    title: 'Superblasters From The Heart',
    description: 'Poppy, psychedelic, dreamy, positive, courageous beginning of some new action-packed space adventure kind of vibes...',
    artist: 'Origami Repetika',
    album: null,
    art: '/images/Origami-Repetika---Superblasters-From-The-Heart.jpeg',
    audio: '/audio/Origami-Repetika---Superblasters-From-The-Heart.mp3',
    duration: '02:19',
    instrumental: true,
    explicit: null,
    genres: 'Pop, Electronic, Psych-Rock, Indie-Rock, Experimental Pop, Instrumental',
    dateReleased: '06/19/2021',
    dateAdded: '06/19/2021',
    url: 'https://freemusicarchive.org/music/Origami_Repetika/2021-tracks/superblasters-from-the-heart',
  },
  {
    id: 'ikth5h',
    title: 'One Hundred Eighty',
    description: 'Poppy, psychedelic, dreamy, positive, courageous beginning of some new action-packed space adventure kind of vibes...',
    artist: 'selfpity',
    album: 'Unhappy Thoughts',
    art: '/images/selfpity---One-Hundred-Eighty.jpeg',
    audio: '/audio/selfpity---One-Hundred-Eighty.mp3',
    duration: '02:16',
    instrumental: false,
    explicit: null,
    genres: 'Pop, Electronic, Indie-Rock, Industrial, Experimental Pop, Dance, Goth, Synth Pop',
    dateReleased: '12/21/2020',
    dateAdded: '12/21/2020',
    url: 'https://freemusicarchive.org/music/selfpity/unhappy-thoughts/one-hundred-eighty',
  },
  {
    id: '5iD4YM',
    title: 'Ashes',
    description: 'Poppy, psychedelic, dreamy, positive, courageous beginning of some new action-packed space adventure kind of vibes...',
    artist: 'Jahzzar',
    album: 'Ashes',
    art: '/images/Jahzzar---Ashes.jpg',
    audio: '/audio/Jahzzar---Ashes.mp3',
    duration: '03:37',
    instrumental: true,
    explicit: null,
    genres: 'Pop, Soul-RnB, Soundtrack',
    dateReleased: '11/29/2018',
    dateAdded: '11/29/2018',
    url: 'https://freemusicarchive.org/music/selfpity/unhappy-thoughts/one-hundred-eighty',
  },
];