const tracks = [
  {
    id: 1,
    title: 'Everybody Keep Running (EDM / Instrumental)',
    description: 'An energetic and inspirational EDM-house track composed by Zight. A song for the post-pandemic world. A gift to all marathon lovers.',
    artist: 'Zight',
    album: null,
    art: '',
    audio: '',
    duration: '02:54',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Pop',
    releaseDate: '10/10/2021',
    url: 'https://freemusicarchive.org/music/zight/single/everybody-keep-running-edm-instrumental',
  },
  {
    id: 2,
    title: 'Fly Away (EDM / Instrumental)',
    description: 'An energetic and inspirational track. Ideal for projects where you need the energy and motivation to pursue freedom.',
    artist: 'Zight',
    album: null,
    art: '',
    audio: '',
    duration: '03:33',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Pop',
    releaseDate: '12/10/2021',
    url: 'https://freemusicarchive.org/music/zight/single/fly-away-edm-instrumental',
  },
  {
    id: 3,
    title: 'Daisy (EDM / Instrumental)',
    description: 'A super catchy electro-pop song. Ideal for media projects targeting young audience.',
    artist: 'Zight',
    album: null,
    art: '',
    audio: '',
    duration: '03:23',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Pop',
    releaseDate: '12/10/2021',
    url: 'https://freemusicarchive.org/music/zight/single/daisy-edm-instrumental',
  },
  {
    id: 4,
    title: 'End Of The Road',
    description: null,
    artist: 'Anthem of Rain',
    album: 'Freedom',
    art: '',
    audio: '',
    duration: '03:23',
    instrumental: false,
    explicit: 'radio-safe',
    genres: 'Pop, Easy Listening, Soul-RnB, Easy Listening: Vocal, hiphop',
    releaseDate: '06/22/2021',
    url: 'https://freemusicarchive.org/music/anthem-of-rain/freedom/end-of-the-road',
  },
  {
    id: 5,
    title: 'All For Nothing',
    description: null,
    artist: 'Anthem of Rain',
    album: 'Freedom',
    art: '',
    audio: '',
    duration: '04:38',
    instrumental: false,
    explicit: 'radio-safe',
    genres: 'International, Pop, Easy Listening, Soundtrack, Easy Listening: Vocal, Piano, Acoustic',
    releaseDate: '06/22/2021',
    url: 'https://freemusicarchive.org/music/anthem-of-rain/freedom/all-for-nothing',
  },
  {
    id: 6,
    title: 'Rock This House',
    description: null,
    artist: 'Anthem of Rain',
    album: 'Freedom',
    art: '',
    audio: '',
    duration: '03:23',
    instrumental: false,
    explicit: 'radio-safe',
    genres: 'International, Pop, Easy Listening, Electronic, Easy Listening: Vocal, Minimal Electronic, Dance',
    releaseDate: '06/22/2021',
    url: 'https://freemusicarchive.org/music/anthem-of-rain/freedom/rock-this-house',
  },
  {
    id: 7,
    title: 'Through My Astrolabe',
    description: 'track from Polyphony Più\'s 2018 Surround Fundamental Shifts and Exhibitions Lp.',
    artist: 'Ov Moi Omm',
    album: null,
    art: '',
    audio: '',
    duration: '03:09',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Pop, Electronic, Experimental Pop, Glitch, Minimal Electronic, Synth Pop',
    releaseDate: '11/14/2021',
    url: 'https://freemusicarchive.org/music/ov-moi-omm/single/through-my-astrolabe',
  },
  {
    id: 8,
    title: 'A Night In Bandung',
    description: 'track from Polyphony Più\'s 2016 Oscillating Illuminations Lp.',
    artist: 'Ov Moi Omm',
    album: null,
    art: '',
    audio: '',
    duration: '03:25',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Field Recordings, Experimental, Electroacoustic, Ambient Electronic, Experimental Pop, Asia',
    releaseDate: '11/14/2021',
    url: 'https://freemusicarchive.org/music/ov-moi-omm/single/a-night-in-bandung',
  },
  {
    id: 9,
    title: 'Within this Sphere lie 71 Stars',
    description: 'track from Polyphony Più\'s 2021 Polyphony Più IV Lp.',
    artist: 'Ov Moi Omm',
    album: null,
    art: '',
    audio: '',
    duration: '12:58',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Avant-Garde, Electronic, Soundtrack, Experimental, Drone, Experimental Pop, Glitch, Downtempo',
    releaseDate: '11/14/2021',
    url: 'https://freemusicarchive.org/music/ov-moi-omm/single/within-this-sphere-lie-71-stars',
  },
  {
    id: 10,
    title: 'All is Shadow and Light',
    description: 'track from Ihsan & The Cabinet of Dr. Caligari\'s 2021 Croquis et thèmes Lp.',
    artist: 'Ov Moi Omm',
    album: null,
    art: '',
    audio: '',
    duration: '03:34',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Noise, Experimental, Ambient Electronic, Glitch, Minimal Electronic',
    releaseDate: '11/13/2021',
    url: 'https://freemusicarchive.org/music/ov-moi-omm/single/all-is-shadow-and-light',
  },
  {
    id: 11,
    title: 'Dirty Infection - Acid Mix',
    description: null,
    artist: 'Arndt Stelter',
    album: null,
    art: '',
    audio: '',
    duration: '04:58',
    instrumental: false,
    explicit: null,
    genres: 'Pop, Electronic, Experimental, Industrial, New Wave, Unclassifiable',
    releaseDate: '10/16/2021',
    url: 'https://freemusicarchive.org/music/arndt-stelter/single/dirty-infection-acid-mix',
  },
  {
    id: 12,
    title: 'Peaces of a Soul',
    description: null,
    artist: 'Arndt Stelter',
    album: null,
    art: '',
    audio: '',
    duration: '05:55',
    instrumental: false,
    explicit: null,
    genres: 'Classical, Soundtrack, Composed Music',
    releaseDate: '10/16/2021',
    url: 'https://freemusicarchive.org/music/arndt-stelter/single/peaces-of-a-soul',
  },
  {
    id: 13,
    title: 'Someone Real',
    description: '"Someone Real" Jenna Jay\'s first single is about wanting new love after going through a toxic relationship full of lies, betrayal, and heartbreak. It spills the raw emotions and pain about hoping to find pure realness in a person again. It talks about finding someone for once who is genuine and doesn\'t put on a fake mask.',
    artist: 'Jenna Jay',
    album: null,
    art: '',
    audio: '',
    duration: '03:49',
    instrumental: false,
    explicit: 'radio-safe',
    genres: 'Pop',
    releaseDate: '08/30/2021',
    url: 'https://freemusicarchive.org/music/jenna-jay/single/someone-real-jenna-jay',
  },
  {
    id: 14,
    title: 'Aqueduct',
    description: null,
    artist: 'Evan Schaeffer',
    album: null,
    art: '',
    audio: '',
    duration: '02:33',
    instrumental: true,
    explicit: null,
    genres: 'Pop, Easy Listening, Electronic',
    releaseDate: '12/08/2021',
    url: 'https://freemusicarchive.org/music/Evan_Schaeffer/Glow_1216/aqueduct',
  },
  {
    id: 15,
    title: 'Chimera',
    description: null,
    artist: 'Evan Schaeffer',
    album: null,
    art: '',
    audio: '',
    duration: '03:43',
    instrumental: false,
    explicit: null,
    genres: 'Pop, Chill-out, Instrumental',
    releaseDate: '08/07/2017',
    url: 'https://freemusicarchive.org/music/Evan_Schaeffer/Big_Splash/Evan_Schaeffer_-_03_-_Chimera',
  },
  {
    id: 16,
    title: 'Chill Breeze',
    description: null,
    artist: 'Evan Schaeffer',
    album: null,
    art: '',
    audio: '',
    duration: '03:27',
    instrumental: false,
    explicit: null,
    genres: 'Pop, Electronic, Instrumental',
    releaseDate: '08/23/2017',
    url: 'https://freemusicarchive.org/music/Evan_Schaeffer/Glow_1216/Evan_Schaeffer_-_14_-_Chill_Breeze_1474',
  },
  {
    id: 17,
    title: 'Slow Burn',
    description: 'Supported by a swing beat, the atmospheric piano track gradually increases to climax in an electronic pop melody. The track is suitable for a wide vareity of explanatory videos, animations and technical videos. Moods: driving, serious, atmospheric, upbeat Licence: "Slow Burn" by Johannes Weber, Fachhochschule Dortmund, CC BY 4.0',
    artist: 'Johannes Weber x Fachhochschule Dortmund',
    album: null,
    art: '',
    audio: '',
    duration: '03:56',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Pop, Easy Listening, Electronic',
    releaseDate: '12/08/2021',
    url: 'https://freemusicarchive.org/music/johannes-weber/single/slow-burn',
  },
  {
    id: 18,
    title: 'Meadow Call',
    description: 'This track is marked by a light and refreshing groove with a melodic climax. Funk elements and a smooth groove embellish a dynamic bassline and a dreamy guitar solo. The track is suitable for all kinds of explanatory videos including introductions, instructional videos, and image clips. Moods: light, refreshing, dynamic, positive, friendly, pleasant, dreamy "Meadow Call" by Jan-Michael Hökenschnieder, Fachhochschule Dortmund, CC BY 4.0',
    artist: 'Jan-Michael Hökenschnieder x Fachhochschule Dortmund',
    album: null,
    art: '',
    audio: '',
    duration: '03:11',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Jazz, Pop, Easy Listening, Funk',
    releaseDate: '12/08/2021',
    url: 'https://freemusicarchive.org/music/jan-michael-hokenschnieder/single/meadow-call',
  },
  {
    id: 19,
    title: 'Digital Tears',
    description: 'Electronic groove track.',
    artist: 'Pariah',
    album: null,
    art: '',
    audio: '',
    duration: '04:59',
    instrumental: true,
    explicit: 'radio-safe',
    genres: 'Pop, Electronic, Soundtrack, Experimental, Ambient Electronic, Radio Art',
    releaseDate: '08/18/2021',
    url: 'https://freemusicarchive.org/music/pariah/single/digital-tears',
  },
  {
    id: 20,
    title: 'Boots & Pants',
    description: null,
    artist: 'Monkey Warhol',
    album: 'Boots & Pants EP',
    art: '',
    audio: '',
    duration: '02:45',
    instrumental: false,
    explicit: null,
    genres: 'Pop, Disco, Electronic, Electro-Punk, Experimental Pop, Techno, Dance, Synth Pop',
    releaseDate: '08/05/2021',
    url: 'https://freemusicarchive.org/music/Monkey_Warhol/boots-pants-ep/boots-pants',
  },
  {
    id: 21,
    title: 'Superblasters From The Heart',
    description: 'Poppy, psychedelic, dreamy, positive, courageous beginning of some new action-packed space adventure kind of vibes...',
    artist: 'Origami Repetika',
    album: null,
    art: '',
    audio: '',
    duration: '02:19',
    instrumental: true,
    explicit: null,
    genres: 'Pop, Electronic, Psych-Rock, Indie-Rock, Experimental Pop, Instrumental',
    releaseDate: '06/19/2021',
    url: 'https://freemusicarchive.org/music/Origami_Repetika/2021-tracks/superblasters-from-the-heart',
  },
  {
    id: 22,
    title: 'One Hundred Eighty',
    description: 'Poppy, psychedelic, dreamy, positive, courageous beginning of some new action-packed space adventure kind of vibes...',
    artist: 'selfpity',
    album: 'Unhappy Thoughts',
    art: '',
    audio: '',
    duration: '02:16',
    instrumental: false,
    explicit: null,
    genres: 'Pop, Electronic, Indie-Rock, Industrial, Experimental Pop, Dance, Goth, Synth Pop',
    releaseDate: '12/21/2020',
    url: 'https://freemusicarchive.org/music/selfpity/unhappy-thoughts/one-hundred-eighty',
  },
  {
    id: 23,
    title: 'Ashes',
    description: 'Poppy, psychedelic, dreamy, positive, courageous beginning of some new action-packed space adventure kind of vibes...',
    artist: 'Jahzzar',
    album: 'Ashes',
    art: '',
    audio: '',
    duration: '03:37',
    instrumental: true,
    explicit: null,
    genres: 'Pop, Soul-RnB, Soundtrack',
    releaseDate: '11/29/2018',
    url: 'https://freemusicarchive.org/music/selfpity/unhappy-thoughts/one-hundred-eighty',
  },
];